### ISSUE TITLE
Multi-project build error: Task with name 'cleanIdeaProject' not found

### ISSUE THREAD

**Issue by remal** [gogradle/gogradle#107]
I have multi-project build and gogradle plugin is applied to one of inner projects.

idea plugin do many things only for root projects, so these tasks can't be found in inner projects:
- cleanIdeaProject
- cleanIdeaWorkspace
- ideaProject
- ideaWorkspace

When I created required tasks, I got NullPointerException exception at com.github.blindpirate.gogradle.ide.IdeaIntegration.hack(IdeaIntegration.java:87)

I'm using Gradle 3.5

**Comment by blindpirate** [comment]
Well, that's a complex scenario, honestly I haven't considered this. Gogradle adds some hacking to idea plugin in order to integrate with IDEA properly, but unfortunately, it only works in root project.

So I guess you are applying idea plugin or importing the projects into IntelliJ IDEA. If you are applying idea plugin, I recommend not to apply it to sub projects. If you are importing it into IDEA, there seems no workaround. Could you please tell me the detailed structure of your project to help me improve Gogradle in next release?

**Comment by remal** [comment]
I have a root project, that is NOT golang project.
I have a sub project, that IS golang project.

In my root project I want to include result of sub project.

**Comment by blindpirate** [comment]
Got it, I think I could let Gogradle more robust in this situation. Thanks for your report, and I will update this ticket when there's any progress.

**Comment by blindpirate** [comment]
I believe this has been solved in latest version. Please let me know if it still exists.
