### ISSUE TITLE
Unrecognized dependency when import and main package share dependencies

### ISSUE THREAD

**Issue by benoitTK** [gogradle/gogradle#141]
We have an application in repo A (testengine/myapp) that we are trying to build.
Files in repo A imports packages B (basics/logger) and C (packets) from our git repo.
so we added the proper dependencies in the build.gradle file.

However package C (packets) also imports package B (basics) and the plugin return an error when trying to resolve the dependencies unless we exclude package B when defining the dependency for B

dependencies {
	golang {
		build name: 'basics', url: "git@<privategitserver>:myrepo/basics.git"
		build (name: 'packets', url: "git@<privategitserver>:testengine/packets.git") 
	}
}
golang {
	packagePath = 'testengine/myapp'
}

If we don't explicitly exclude the package, go gradle plugin reports the following error:

* What went wrong:
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
  Cannot recognized package: basics/logger
  Resolution stack is:
  +- testengine/myapp
   +- packets#198fda830716c5848e1e50af386e3d92b65a2626

Is this a known bug?

We have found  workarounds but none is fully satisfactory.  
The first one is to exclude B when import C
We can exclude the import from packets by using the exclude clause

		build (name: 'packets', url: "git@<privategitserver>:testengine/packets.git") {
			exclude name: 'myrepo/basics'
		}

The issue with this solution is that if the C package developer adds new dependencies conflicting with A dependencies, that will break A build.

The other solution is to use transitive = false.
Here the issue is that if C adds new import/dependencies, A will not have them and it will break the build.

The best would be that the go gradle plugin recognize the package and resolve it properly.

Any hints?

We are using gradle 3.4.1 and go plugin 0.5.0.
We tried also with gradle 4.0 and go plugin 0.7.0 but we faced the exact same error.

**Comment by blindpirate** [comment]
Thanks for reporting this.

I have totally understood what you said. It should be improved.

The reason is, `basics/logger` is not a "legal" golang package (which means that we can't get code based on `basics/logger` from a remote location, according to [here](https://golang.org/cmd/go/#hdr-Remote_import_paths)). However, since you have already specified `basics`, this should not fail.

A slightly more elegant solution (for the moment) is, 

```
repositories {
    golang {
         root 'basics'
         url 'git@:myrepo/basics.git'
    }
}
```

See [here](https://github.com/gogradle/gogradle/blob/master/docs/repository-management.md) for more detail.

I will fix this issue in next release.

**Comment by blindpirate** [comment]
Hi, I'll close it for the moment, please feel free to reopen it if any issue still exists.
