### ISSUE TITLE
cannot find package "fmt"

### ISSUE THREAD

**Issue by sbulman** [gogradle/gogradle#154]
On a Windows machine, if I specify goVersion and that version does not exist locally then gradlew.bat build fails with the message 'cannot find package "fmt"'. A little searching would suggest this has something to do with a bad set up of GOROOT.

As expected, the specified version of Go is downloaded to the .gradle directory in my User folder and gradlew.bat showGopathGoroot appears to report the correct path

GOPATH: C:/workspace
GOROOT: C:/Users/Simon/.gradle/go/binary/1.9.2/go

If I don't specify a goVersion, gogradle detects my local version (1.8.3) and build succeeds.

Any ideas?

Thanks,
Simon

**Comment by blindpirate** [comment]
Thanks for reporting. You mean the `GOROOT` `showGopathGoroot` task reported is correct, but the `GOROOT` used in the build is wrong? That's interesting because AFAIK they should be same. Could you tell me what's the `GOROOT` actually used in build? 

P.S. you could set `goRoot` in the same way as `goVersion`: https://github.com/gogradle/gogradle/blob/master/docs/getting-started.md#configuration

**Comment by sbulman** [comment]
I don't know if GOROOT for the build is different. I mentioned GOROOT because a search for the error message suggested this happens when GOROOT is set up incorrectly.

I have tried to reproduce the problem this morning and can't. After reporting this issue, I uninstalled my older local version of Go and installed the version I wanted to use. Now, I am able to change the goVersion in the build file and it works. So I think this may have been something to do with my old installation. If I see it again, I'll add some more info, but for now you can close this issue.

Thanks,
Simon

**Comment by blindpirate** [comment]
OK, let's wait for it happening again. :-)
