### ISSUE TITLE
SSLException for resolveBuildDependencies task

### ISSUE THREAD

**Issue by eleito** [gogradle/gogradle#235]
Running `clean build` produces this exception and it is found on some Mac machines, but on other machines, these tasks work fine. Any ideas why? Log file is attached.

[go-gradle-issue](https://github.com/paulvanderende/go-gradle-issue) is used for reproducing this error. Gradle version info:

Gradle 4.8.1

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Mac OS X 10.13.5 x86_64

[Log gogradle SSLException.txt](https://github.com/gogradle/gogradle/files/2176035/Log.gogradle.SSLException.txt)
### Error:
> Task :resolveBuildDependencies FAILED
Exception in accessing https://gopkg.in/yaml.v2
javax.net.ssl.SSLException: Received fatal alert: internal_error

Hack for solving this issue was to use the gogradle dependency created on a machine that worked and put it into `/Users/macuser/.gradle/go/repo`.

**Comment by blindpirate** [comment]
It works fine for me as well. I think this is due to the wrong configuration of your JVM. It has nothing to do with Gogradle as well as Gradle. Could you please try to put only this line in your `build.gradle` and retry?

```
'https://gopkg.in/yaml.v2'.toURL().text
```

If it fails as well, you can run `./gradlew -Djavax.net.debug=all` to get some diagnosis output, which can tell you what's wrong.
